### ISSUE TITLE
Module build failed

### ISSUE THREAD

**Issue by Makanz** [glaubervictor/InspiniaReact#1]
When I run `npm run dev` i get the following error.

ERROR in ./src/index.jsx
Module build failed: SyntaxError: C:\Users\Name\Desktop\package.json: Unexpected token : in JSON at position 44
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:679:27)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at find (C:\Users\Name\Desktop\_Temp\inspinia\node_modules\babel-loader\lib\resolve-rc.js:14:49)
    at find (C:\Users\Name\Desktop\_Temp\inspinia\node_modules\babel-loader\lib\resolve-rc.js:24:12)
    at find (C:\Users\Name\Desktop\_Temp\inspinia\node_modules\babel-loader\lib\resolve-rc.js:24:12)
 @ multi (webpack)-dev-server/client?http://localhost:8081 webpack/hot/dev-server babel-polyfill ./src/index.jsx

**Comment by glaubervictor** [comment]
Hello you can follow the following steps:

`git clone https://github.com/glaubervictor/InspiniaReact.git`

then go to the folder 

> InspiniaReact

and run the command: `npm install`
and finally run the command: `npm run dev`

access the site at 

> localhost: 8080

Hope this helps.
